package com.phonediagnostic.data

import java.util.Locale

object ReportExporter {

    fun toShareText(report: FullDeviceReport): String {
        val o = report.overview
        val c = report.cpu
        val g = report.gpu
        val b = report.battery
        val m = report.memory
        val n = report.network
        val s = report.storage
        val d = report.display

        return buildString {
            appendLine("Phone Diagnostic Report")
            appendLine("========================")
            appendLine()
            appendLine("DEVICE")
            appendLine("  Manufacturer: ${o.manufacturer}")
            appendLine("  Model: ${o.model}")
            appendLine("  Brand: ${o.brand}")
            appendLine("  Android: ${o.androidVersion} (API ${o.apiLevel})")
            appendLine("  Security Patch: ${o.securityPatch}")
            appendLine("  Build ID: ${o.buildId}")
            appendLine("  Uptime: ${o.uptime}")
            appendLine()
            appendLine("CPU / SoC")
            appendLine("  Cores: ${c.cores}")
            appendLine("  Architecture: ${c.architecture}")
            appendLine("  Hardware: ${c.hardware}")
            appendLine("  Processor: ${c.processor}")
            appendLine("  ABIs: ${c.supportedAbis.joinToString(", ")}")
            appendLine()
            appendLine("GPU")
            appendLine("  Renderer: ${g.renderer}")
            appendLine("  Vendor: ${g.vendor}")
            appendLine("  Version: ${g.version}")
            appendLine()
            appendLine("BATTERY")
            appendLine("  Level: ${b.level}%")
            appendLine("  Status: ${b.status}")
            appendLine("  Health: ${b.health}")
            appendLine("  Temperature: ${String.format(Locale.US, "%.1f", b.temperature)} °C")
            appendLine("  Voltage: ${b.voltage} mV")
            appendLine("  Technology: ${b.technology}")
            appendLine("  Power Source: ${b.powerSource}")
            appendLine()
            appendLine("MEMORY (RAM)")
            appendLine("  Total: ${m.totalRamMb} MB")
            appendLine("  Available: ${m.availableRamMb} MB")
            appendLine("  Used: ${m.usedRamMb} MB (${m.usagePercent}%)")
            appendLine()
            appendLine("NETWORK")
            appendLine("  Connection: ${if (n.isConnected) "Connected" else "Disconnected"}")
            appendLine("  Type: ${n.networkType}")
            appendLine("  Latency: ${n.latencyMs?.let { "$it ms" } ?: "—"}")
            appendLine("  Target: ${n.latencyTarget}")
            appendLine("  Status: ${n.latencyStatus}")
            appendLine()
            appendLine("STORAGE")
            appendLine("  Total: ${String.format(Locale.US, "%.2f", s.totalInternalGb)} GB")
            appendLine("  Free: ${String.format(Locale.US, "%.2f", s.freeInternalGb)} GB")
            appendLine("  Used: ${String.format(Locale.US, "%.2f", s.usedInternalGb)} GB (${s.usagePercent}%)")
            appendLine()
            appendLine("DISPLAY")
            appendLine("  Resolution: ${d.widthPx} × ${d.heightPx}")
            appendLine("  Density: ${d.densityDpi} dpi")
            appendLine("  Refresh Rate: ${String.format(Locale.US, "%.1f", d.refreshRate)} Hz")
            appendLine("  Approx. Size: ${String.format(Locale.US, "%.2f", d.screenSizeInches)}\"")
            appendLine()
            appendLine("Generated by Phone Diagnostic Tool")
        }
    }
}
