package com.phonediagnostic.data

import org.json.JSONArray
import org.json.JSONObject
import java.util.Locale

object ReportExporter {

    fun toShareText(report: FullDeviceReport): String {
        val o = report.overview
        val c = report.cpu
        val g = report.gpu
        val b = report.battery
        val m = report.memory
        val n = report.network
        val s = report.storage
        val d = report.display

        return buildString {
            appendLine("Phone Diagnostic Report")
            appendLine("========================")
            appendLine()
            appendLine("DEVICE")
            appendLine("  Manufacturer: ${o.manufacturer}")
            appendLine("  Model: ${o.model}")
            appendLine("  Brand: ${o.brand}")
            appendLine("  Android: ${o.androidVersion} (API ${o.apiLevel})")
            appendLine("  Security Patch: ${o.securityPatch}")
            appendLine("  Build ID: ${o.buildId}")
            appendLine("  Uptime: ${o.uptime}")
            appendLine()
            appendLine("CPU / SoC")
            appendLine("  Cores: ${c.cores}")
            appendLine("  Architecture: ${c.architecture}")
            appendLine("  Board / Platform: ${c.boardPlatform}")
            appendLine("  Hardware: ${c.hardware}")
            appendLine("  Processor: ${c.processor}")
            appendLine("  ABIs: ${c.supportedAbis.joinToString(", ")}")
            appendLine()
            appendLine("GPU")
            appendLine("  Renderer: ${g.renderer}")
            appendLine("  Vendor: ${g.vendor}")
            appendLine("  Version: ${g.version}")
            appendLine()
            appendLine("BATTERY")
            appendLine("  Level: ${b.level}%")
            appendLine("  Status: ${b.status}")
            appendLine("  Health: ${b.health}")
            appendLine("  Temperature: ${String.format(Locale.US, "%.1f", b.temperature)} °C")
            appendLine("  Voltage: ${b.voltage} mV")
            appendLine("  Current (now): ${b.currentNowMa?.let { "$it mA" } ?: "Unavailable"}")
            appendLine("  Current (avg): ${b.currentAvgMa?.let { "$it mA" } ?: "Unavailable"}")
            appendLine("  Technology: ${b.technology}")
            appendLine("  Power Source: ${b.powerSource}")
            appendLine()
            appendLine("MEMORY (RAM)")
            appendLine("  Total: ${m.totalRamMb} MB")
            appendLine("  Available: ${m.availableRamMb} MB")
            appendLine("  Used: ${m.usedRamMb} MB (${m.usagePercent}%)")
            appendLine()
            appendLine("NETWORK")
            appendLine("  Connection: ${if (n.isConnected) "Connected" else "Disconnected"}")
            appendLine("  Type: ${n.networkType}")
            appendLine("  Latency: ${n.latencyMs?.let { "$it ms" } ?: "—"}")
            appendLine("  Target: ${n.latencyTarget}")
            appendLine("  Status: ${n.latencyStatus}")
            appendLine()
            appendLine("STORAGE")
            appendLine("  Total: ${String.format(Locale.US, "%.2f", s.totalInternalGb)} GB")
            appendLine("  Free: ${String.format(Locale.US, "%.2f", s.freeInternalGb)} GB")
            appendLine("  Used: ${String.format(Locale.US, "%.2f", s.usedInternalGb)} GB (${s.usagePercent}%)")
            appendLine()
            appendLine("DISPLAY")
            appendLine("  Resolution: ${d.widthPx} × ${d.heightPx}")
            appendLine("  Density: ${d.densityDpi} dpi")
            appendLine("  Refresh Rate: ${String.format(Locale.US, "%.1f", d.refreshRate)} Hz")
            appendLine("  Approx. Size: ${String.format(Locale.US, "%.2f", d.screenSizeInches)}\"")
            appendLine()
            appendLine("Generated by Phone Diagnostic Tool")
            appendLine("Privacy: on-device diagnostics; optional latency probe only.")
        }
    }

    fun toJson(report: FullDeviceReport): String {
        val o = report.overview
        val c = report.cpu
        val g = report.gpu
        val b = report.battery
        val m = report.memory
        val n = report.network
        val s = report.storage
        val d = report.display

        val root = JSONObject()
        root.put("app", "Phone Diagnostic Tool")
        root.put("overview", JSONObject().apply {
            put("manufacturer", o.manufacturer)
            put("model", o.model)
            put("brand", o.brand)
            put("androidVersion", o.androidVersion)
            put("apiLevel", o.apiLevel)
            put("securityPatch", o.securityPatch)
            put("buildId", o.buildId)
            put("uptime", o.uptime)
        })
        root.put("cpu", JSONObject().apply {
            put("cores", c.cores)
            put("architecture", c.architecture)
            put("boardPlatform", c.boardPlatform)
            put("hardware", c.hardware)
            put("processor", c.processor)
            put("supportedAbis", JSONArray(c.supportedAbis))
        })
        root.put("gpu", JSONObject().apply {
            put("renderer", g.renderer)
            put("vendor", g.vendor)
            put("version", g.version)
        })
        root.put("battery", JSONObject().apply {
            put("level", b.level)
            put("status", b.status)
            put("health", b.health)
            put("temperatureC", b.temperature)
            put("voltageMv", b.voltage)
            put("currentNowMa", b.currentNowMa ?: JSONObject.NULL)
            put("currentAvgMa", b.currentAvgMa ?: JSONObject.NULL)
            put("technology", b.technology)
            put("powerSource", b.powerSource)
        })
        root.put("memory", JSONObject().apply {
            put("totalRamMb", m.totalRamMb)
            put("availableRamMb", m.availableRamMb)
            put("usedRamMb", m.usedRamMb)
            put("usagePercent", m.usagePercent)
        })
        root.put("network", JSONObject().apply {
            put("isConnected", n.isConnected)
            put("networkType", n.networkType)
            put("latencyMs", n.latencyMs ?: JSONObject.NULL)
            put("latencyTarget", n.latencyTarget)
            put("latencyStatus", n.latencyStatus)
        })
        root.put("storage", JSONObject().apply {
            put("totalInternalGb", s.totalInternalGb)
            put("freeInternalGb", s.freeInternalGb)
            put("usedInternalGb", s.usedInternalGb)
            put("usagePercent", s.usagePercent)
        })
        root.put("display", JSONObject().apply {
            put("widthPx", d.widthPx)
            put("heightPx", d.heightPx)
            put("densityDpi", d.densityDpi)
            put("density", d.density)
            put("refreshRate", d.refreshRate)
            put("screenSizeInches", d.screenSizeInches)
        })
        return root.toString(2)
    }
}
